apiVersion: v2
appVersion: 5.3.0
description: RocketMQ Helm chart
keywords:
- rocketmq
- kubernetes
- apache
maintainers:
- name: itboon
  url: https://github.com/itboon/rocketmq-helm
name: rocketmq
type: application
version: 12.3.2
